# Host: localhost  (Version: 5.5.47)
# Date: 2017-10-12 11:04:50
# Generator: MySQL-Front 5.3  (Build 1.27)

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE */;
/*!40101 SET SQL_MODE='NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES */;
/*!40103 SET SQL_NOTES='ON' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS */;
/*!40014 SET FOREIGN_KEY_CHECKS=0 */;

#
# Source for table "zcgl_mx"
#

DROP TABLE IF EXISTS `zcgl_mx`;
CREATE TABLE `zcgl_mx` (
  `bh` varchar(24) NOT NULL DEFAULT '' COMMENT '资产编号',
  `name` varchar(24) NOT NULL DEFAULT '' COMMENT '资产名称',
  `pp` varchar(24) NOT NULL DEFAULT '' COMMENT '品牌',
  `xh` varchar(24) NOT NULL DEFAULT '' COMMENT '型号规格',
  `sybm` varchar(24) NOT NULL DEFAULT '' COMMENT '使用部门',
  `cfdd` varchar(24) NOT NULL DEFAULT '' COMMENT '存放地点',
  `jg` varchar(24) NOT NULL DEFAULT '' COMMENT '价格',
  `gzsj` varchar(24) NOT NULL DEFAULT '' COMMENT '购置时间',
  `jysj` varchar(24) NOT NULL DEFAULT '' COMMENT '借用时间',
  `bz` varchar(128) NOT NULL DEFAULT '' COMMENT '备注',
  `zrr` varchar(24) NOT NULL DEFAULT '' COMMENT '责任人',
  `lb` varchar(24) NOT NULL DEFAULT '' COMMENT '类别',
  `ly` varchar(24) NOT NULL DEFAULT '' COMMENT '资产来源',
  `zt` varchar(24) NOT NULL DEFAULT '' COMMENT '状态',
  PRIMARY KEY (`bh`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='资产明细';

#
# Data for table "zcgl_mx"
#

/*!40000 ALTER TABLE `zcgl_mx` DISABLE KEYS */;
/*!40000 ALTER TABLE `zcgl_mx` ENABLE KEYS */;

/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
